### ISSUE TITLE
hiipack.pac提示找不到

### ISSUE THREAD

**Issue by zhouhailong** [zdying/hiipack#10]
日志如下
hiipack proxy file file:///var/folders/r9/pyf_2pnn67lchv0jsq3wxxjm0000gn/T/hiipack_cache/hiipack.pac

[error] proxy -> Server - ENOENT: no such file or directory, open '/var/folders/r9/pyf_2pnn67lchv0jsq3wxxjm0000gn/T/hiipack_cache/hiipack.pac'

大概是临时目录被清空了，找不到文件

**Comment by zdying** [comment]
fixed. 

:)
