### ISSUE TITLE
favicon.ico提示错误

### ISSUE THREAD

**Issue by zhouhailong** [zdying/hiipack#11]
[error] Server - ENOENT: no such file or directory, stat '/example/path/index.htmlfavicon.ico'

**Comment by zdying** [comment]
rewrite配置问题。

**Comment by zdying** [comment]
```
location / {
    proxy_pass http://$local/joke_new/view/index.html;
}
```
这个配置直接把`/`转发到一个具体的文件，导致出现的问题
