### ISSUE TITLE
hii min 打包的lib文件中有多余的环境判断

### ISSUE THREAD

**Issue by huaziHear** [zdying/hiipack#5]
使用hii min打包文件之后，文件中有大量的类似"production"!==t.env.NODE_ENV 的判断，这个点是必须的无法避免的还是可以优化的部分。

**Comment by zdying** [comment]
Webpack没有处理，hii也没有处理，因为不能保证判断环境的代码是没有用的。

但是有一种思路是打包第三方模块压缩后的代码，比如用`react/dist/react.min.js`替代`react`。

另外一种是： 使用`alias`, 比如：

``` javascript
alias: {
     'react': 'react/dist/react.min.js'
}
```

**Comment by zdying** [comment]
@huaziHear 测试了一下，在非`library`里面文件是不会有`"production"!==t.env.NODE_ENV`这样的代码的，之所以react代码里面有，是因为打包`library`代码时没有设置环境变量，稍后修复。
